"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

memo = {}
def fibonacci(n):
    if n in memo:
        return memo[n]
    else:
        if n <= 2:
            f = n
        else:
            f = fibonacci(n-2) + fibonacci(n-1)
        memo[n] = f
        return f

sum = 0
initial = 1      
while True:
    value = fibonacci(initial)
    if value >= 4000000:
        break
    else:
        if value % 2 == 0:
            sum = sum + value
        initial += 1
print (sum)